# Generated by Django 2.1.3 on 2018-11-21 12:57

from django.db import migrations, models
import localflavor.nl.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('PhoneNumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('Email', models.EmailField(max_length=50)),
                ('PostalCode', localflavor.nl.models.NLZipCodeField(max_length=7)),
                ('City', models.CharField(max_length=50)),
                ('Street', models.CharField(max_length=50)),
                ('HouseNumber', models.CharField(max_length=10)),
            ],
        ),
    ]
